#!/bin/bash

error='\033[37m\033[41m'
success='\033[30m\033[42m'
warning='\033[30m\033[43m'
info='\033[37m\033[44m'
blue='\033[34m'
yellow='\033[33m'
green='\033[32m'
clr='\033[0m'
verbose=false
full_install=false
uid=$(id -u)
gid=$(id -g)

function check_requirements {
    if ! command -v docker &> /dev/null
    then
        echo ''
        echo -e "$error        $clr"
        echo -e "$error Error! $clr ${yellow}Docker$clr could not be found. Install it at ${yellow}https://www.docker.com/get-started$clr"
        echo -e "$error        $clr"
        exit
    fi

    if ! command -v docker-compose &> /dev/null
    then
        echo ''
        echo -e "$error        $clr"
        echo -e "$error Error! $clr ${yellow}docker-compose$clr could not be found. Install it at ${yellow}https://docs.docker.com/compose/install/$clr"
        echo -e "$error        $clr"
        exit
    fi
}

function usage {
    {
        echo "$1" | grep -Pq '^(?!-+)[\w_-]+$'
        RESULT=$?
    } &> /dev/null

    if [ $# -eq 0 ] || [ $RESULT -gt 0 ]; then
        echo ''
        echo -e "$warning        $clr"
        echo -e "$warning Usage: $clr ${yellow}install$clr my_project [options]"
        echo -e "$warning        $clr"
        echo ''
        echo -e "${yellow}Options:$clr"
        echo -e "  ${green}-f, --full-install$clr  Run the complete installation including containers creation"
        echo -e "  ${green}-v, --verbose$clr       Verbose output"
        echo ''
        exit
    fi
}

function parse_options {
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -f|--full-install) full_install=true ;;
            -v|--verbose) verbose=true ;;
        esac
        shift
    done
}

function spinner {
    chars="◐◓◑◒"

    while :; do
        for (( i=0; i<${#chars}; i++ )); do
            sleep 0.5
            echo -en "$1 ${chars:$i:1}" "\r"
        done
    done
}

function dcomposer {
    docker run --rm --name numbernine_installer -u "$uid:$gid" \
        -e SYMFONY_ENDPOINT=https://flex.symfony.com/r/github.com/symfony/recipes-contrib/1049 \
        -v "$PWD":/srv/app -w /srv/app numberninecms/php:7.4-fpm-dev composer "$@";
}

function execute {
    if [ $verbose = true ] ; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

function main {
    check_requirements
    usage "$@"
    parse_options "$@"

    tput civis

    echo ''
    echo -e "$success                                                                                                                        $clr"
    echo -e "$success NumberNine installation in progress                                                                                    $clr"
    echo -e "$success                                                                                                                        $clr"
    echo ''
    echo "Creating new project in ./$1 directory."
    spinner 'Please wait while preparing your project...' &
    PID=$!

    execute mkdir -p "$1" && cd "$1" || exit
    execute dcomposer create-project symfony/website-skeleton .
    execute dcomposer config extra.symfony.allow-contrib true
    execute dcomposer req numberninecms/numbernine

    kill $PID
    tput cnorm

    if [ $full_install = true ]; then
        if [ $verbose = true ]; then
            verbosity='-v'
        fi
        echo ''
        echo ''
        echo 'Installing Docker environment...'
        echo ''
        bin/console numbernine:docker:install --app-name="$1" $verbosity
        echo ''
        echo -e "$info                             $clr"
        echo -e "$info What's next?                $clr"
        echo -e "$info                             $clr"
        echo ''
        echo -e "  * ${blue}Read$clr the documentation at ${yellow}https://numberninecms.github.io/$clr"
    else
        echo ''
        echo ''
        echo -e "$info                             $clr"
        echo -e "$info     You're almost ready     $clr"
        echo -e "$info                             $clr"
        echo ''
        echo -e "  * ${blue}Run ${yellow}cd $1 && php bin/console numbernine:docker:install$clr"
        echo ''
        echo -e "  * ${blue}Read$clr the documentation at ${yellow}https://numberninecms.github.io/$clr"
    fi
}

main "$@"
