#!/bin/bash

if ! command -v docker &> /dev/null
then
    echo ''
    echo -e '\033[37m\033[41m        \033[0m'
    echo -e '\033[37m\033[41m Error! \033[0m \033[33mDocker\033[0m could not be found. Install it at \033[33mhttps://www.docker.com/get-started\033[0m'
    echo -e '\033[37m\033[41m        \033[0m'
    exit
fi

if ! command -v docker-compose &> /dev/null
then
    echo ''
    echo -e '\033[37m\033[41m        \033[0m'
    echo -e '\033[37m\033[41m Error! \033[0m \033[33mdocker-compose\033[0m could not be found. Install it at \033[33mhttps://docs.docker.com/compose/install/\033[0m'
    echo -e '\033[37m\033[41m        \033[0m'
    exit
fi

{
    echo "$1" | grep -Pq '^(?!-+)[\w_-]+$'
    RESULT=$?
} &> /dev/null

if [ $# -eq 0 ] || [ $# -gt 2 ] || [ $RESULT -gt 0 ]; then
    echo ''
    echo -e '\033[30m\033[43m        \033[0m'
    echo -e '\033[30m\033[43m Usage: \033[0m \033[33minstall\033[0m my_project \033[36m--full-install\033[0m'
    echo -e '\033[30m\033[43m        \033[0m'
    exit
fi

function spinner {
    chars="◐◓◑◒"

    while :; do
        for (( i=0; i<${#chars}; i++ )); do
            sleep 0.5
            echo -en "$1 ${chars:$i:1}" "\r"
        done
    done
}

function dcomposer {
    docker run --rm --name numbernine_installer -u '1000:1000' \
        -e SYMFONY_ENDPOINT=https://flex.symfony.com/r/github.com/symfony/recipes-contrib/1049 \
        -v $PWD:/srv/app -w /srv/app numberninecms/php:7.4-fpm-dev composer $@;
}

tput civis

echo ''
echo -e '\033[30m\033[42m                                                                                                                        \033[0m'
echo -e '\033[30m\033[42m NumberNine installation in progress                                                                                    \033[0m'
echo -e '\033[30m\033[42m                                                                                                                        \033[0m'
echo ''
echo "Creating new project in ./$1 directory."
spinner 'Please wait while preparing your project...' &
PID=$!

{
    mkdir -p $1 && cd $1
    dcomposer create-project symfony/website-skeleton .
    dcomposer config extra.symfony.allow-contrib true
    dcomposer req numberninecms/numbernine
} &> /dev/null

kill $PID
tput cnorm

if [ "$2" = "--full-install" ]; then
    echo ''
    echo ''
    echo 'Installing Docker environment...'
    echo ''
    bin/console numbernine:docker:install
    echo ''
    echo -e '\033[37m\033[44m                             \033[0m'
    echo -e "\033[37m\033[44m What's next?                \033[0m"
    echo -e '\033[37m\033[44m                             \033[0m'
    echo ''
    echo -e '  * \033[34mRead\033[0m the documentation at \033[33mhttps://numberninecms.github.io/\033[0m'
else
    echo ''
    echo ''
    echo -e '\033[37m\033[44m                             \033[0m'
    echo -e "\033[37m\033[44m     You're almost ready     \033[0m"
    echo -e '\033[37m\033[44m                             \033[0m'
    echo ''
    echo -e "  * \033[34mRun \033[33mcd $1 && php bin/console numbernine:docker:install\033[0m"
    echo ''
    echo -e '  * \033[34mRead\033[0m the documentation at \033[33mhttps://numberninecms.github.io/\033[0m'
fi
